In [ ]:
import pandas as pd
import numpy as np

1. > Create a Pandas series from a list and then from an array, having 4 numbers and choose the first letters of the alphabet for their index

In [ ]:
my_list=[1,2,3,4]

my_array=np.array([1,2,3,4])

In [ ]:
my_array

array([1, 2, 3, 4])

In [ ]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
pd.Series(   my_list, index=(['11','12','13','14'])   )

11    1
12    2
13    3
14    4
dtype: int64

In [ ]:
dd={'A':1,'B':2}

In [ ]:

pd.Series(   my_array,    index=['A','B','C','D']    )

A    1
B    2
C    3
D    4
dtype: int64

2. > Create a Series just like above, but from a dictionary

In [ ]:
my_dict={'A':1,'B':2,'C':3,'D':4}  # creating a dictionary

In [ ]:
pd.Series(my_dict)   # feeding the Series function from pandas with the above dictyionary

A    1
B    2
C    3
D    4
dtype: int64

3. >  Use the label and the index to choose the second item in the Series you create

In [ ]:
my_series=pd.Series(my_dict)

In [ ]:
my_series

A    1
B    2
C    3
D    4
dtype: int64

In [ ]:
my_series['B']

2

In [ ]:
my_series['D']

4

In [ ]:
my_series[1]

2

> Data Frames

4. > Create a 4 by 4 random matrix and then create a data frame from it, with index values being A,B C, D and the column names being  W,X,Y ,Z

In [ ]:
np.random.seed(44) # use this if you want to keep getting same random numbers

In [ ]:

#np.random.seed(44)
np.random.randint(0,10,(4,4))

array([[4, 3, 1, 3],
       [0, 4, 3, 8],
       [7, 7, 6, 9],
       [3, 7, 3, 3]])

In [ ]:
dd=np.random.randint(0,10,(4,4))

In [ ]:
dd

array([[6, 5, 4, 5],
       [9, 1, 8, 7],
       [4, 5, 3, 0],
       [4, 9, 2, 8]])

In [ ]:


#pd.DataFrame(np.random.randint(0,10,(4,4)), index=['A','B','C','D'], columns=['W','X','Y','Z'])
pd.DataFrame(dd, index=['A','B','C','D'], columns=['W','X','Y','Z'])

W  X  Y  Z
A  6  5  4  5
B  9  1  8  7
C  4  5  3  0
D  4  9  2  8

OR

In [ ]:
i=['A','B','C','D']
c=['W','X','Y','Z']

my_mat=np.random.randint(0,10,(4,4))

In [ ]:
my_mat

array([[8, 6, 2, 0],
       [3, 4, 8, 3],
       [2, 2, 1, 2],
       [2, 9, 8, 1]])

In [ ]:
pd.DataFrame(my_mat,i,c)  # the function takes ( DATA   ,   Rows   ,  Colmns)

W  X  Y  Z
A  8  6  2  0
B  3  4  8  3
C  2  2  1  2
D  2  9  8  1

from matplotlib import pyplot as plt
_df_0['W'].plot(kind='hist', bins=20, title='W')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['X'].plot(kind='hist', bins=20, title='X')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Y'].plot(kind='hist', bins=20, title='Y')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Z'].plot(kind='hist', bins=20, title='Z')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='W', y='X', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='X', y='Y', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Y', y='Z', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7['W'].plot(kind='line', figsize=(8, 4), title='W')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_8['X'].plot(kind='line', figsize=(8, 4), title='X')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Y'].plot(kind='line', figsize=(8, 4), title='Y')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Z'].plot(kind='line', figsize=(8, 4), title='Z')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df=pd.DataFrame(my_mat,i,c)

In [ ]:
df

W  X  Y  Z
A  8  6  2  0
B  3  4  8  3
C  2  2  1  2
D  2  9  8  1

In [ ]:
df['Z']  #stick to this for the moment

A    0
B    3
C    2
D    1
Name: Z, dtype: int64

In [ ]:
df.W

A    2
B    1
C    5
D    3
Name: W, dtype: int64

5. > Get Some statistics from your Data Frame

In [ ]:
df=pd.DataFrame(my_mat,i,c)

In [ ]:
df.describe()

W         X         Y         Z
count  4.000000  4.000000  4.000000  4.000000
mean   3.750000  5.250000  4.750000  1.500000
std    2.872281  2.986079  3.774917  1.290994
min    2.000000  2.000000  1.000000  0.000000
25%    2.000000  3.500000  1.750000  0.750000
50%    2.500000  5.000000  5.000000  1.500000
75%    4.250000  6.750000  8.000000  2.250000
max    8.000000  9.000000  8.000000  3.000000

In [ ]:
pd.DataFrame(my_mat,i,c).describe()

W         X         Y         Z
count  4.000000  4.000000  4.000000  4.000000
mean   3.750000  5.250000  4.750000  1.500000
std    2.872281  2.986079  3.774917  1.290994
min    2.000000  2.000000  1.000000  0.000000
25%    2.000000  3.500000  1.750000  0.750000
50%    2.500000  5.000000  5.000000  1.500000
75%    4.250000  6.750000  8.000000  2.250000
max    8.000000  9.000000  8.000000  3.000000

or

In [ ]:
my_df=pd.DataFrame(my_mat,i,c)

In [ ]:
my_df.describe()

W         X         Y         Z
count  4.000000  4.000000  4.000000  4.000000
mean   3.750000  5.250000  4.750000  1.500000
std    2.872281  2.986079  3.774917  1.290994
min    2.000000  2.000000  1.000000  0.000000
25%    2.000000  3.500000  1.750000  0.750000
50%    2.500000  5.000000  5.000000  1.500000
75%    4.250000  6.750000  8.000000  2.250000
max    8.000000  9.000000  8.000000  3.000000

6. >transpose the statsitics table you created above ( for better visualisation)

In [ ]:
my_df.describe().T  # with .T

count  mean       std  min   25%  50%   75%  max
W    4.0  3.75  2.872281  2.0  2.00  2.5  4.25  8.0
X    4.0  5.25  2.986079  2.0  3.50  5.0  6.75  9.0
Y    4.0  4.75  3.774917  1.0  1.75  5.0  8.00  8.0
Z    4.0  1.50  1.290994  0.0  0.75  1.5  2.25  3.0

7. > Choose the items in first and third columns of your data Frame

In [ ]:
my_df

W  X  Y  Z
A  8  6  2  0
B  3  4  8  3
C  2  2  1  2
D  2  9  8  1

In [ ]:
asad = my_df[['W','Y']]
asad

W  Y
A  8  2
B  3  8
C  2  1
D  2  8

In [ ]:
type(my_df[['W']])

pandas.core.frame.DataFrame

In [ ]:
my_df[['W']]

W
A  2
B  1
C  5
D  3

In [ ]:
my_df[['W','Y']]  # notice the double brackets (a list of col names is given)

W  Y
A  7  3
B  1  2
C  3  0
D  6  9

or

In [ ]:
my_df

W  X  Y  Z
A  2  3  4  8
B  1  7  9  8
C  5  4  7  3
D  3  8  1  1

In [ ]:
my_df.iloc[    :    ,   [0,2]]   #    [   rows    , cols             ]

W  Y
A  2  4
B  1  9
C  5  7
D  3  1

8. > Select the 2nd and 3rd rows of the dataframe

In [ ]:
my_df.iloc[[1,2],:]

W  X  Y  Z
B  1  3  2  4
C  3  4  0  3

9. > Select Row A  first , the select row A and D

In [ ]:
my_df

W  X  Y  Z
A  2  3  4  8
B  1  7  9  8
C  5  4  7  3
D  3  8  1  1

In [ ]:
my_df.loc[['A']]   # for selecting rows  use .loc [     ]

W  X  Y  Z
A  2  3  4  8

In [ ]:
my_df.loc[['A','D']]

W  X  Y  Z
A  7  5  3  5
D  6  6  9  0

10. > Select ONLY THE VALUES in the 2nd and 3rd rows of the dataframe

In [ ]:
type(my_df.iloc[[1,2],:])

pandas.core.frame.DataFrame

In [ ]:
type(my_df.iloc[[1,2],:].values)   # Notice that now, you only have a Numpy array output

numpy.ndarray

11. Create a new column that sums up the values in column W and Z

In [ ]:
my_df

W  X  Y  Z
A  2  3  4  8
B  1  7  9  8
C  5  4  7  3
D  3  8  1  1

In [ ]:
my_df['New']                       =    my_df['W']    +     my_df['Z']

In [ ]:
my_df

W  X  Y  Z  New
A  7  5  3  5   12
B  1  3  2  4    5
C  3  4  0  3    6
D  6  6  9  0    6

12. >Get rid of the new column TEMPORARILY

In [ ]:
my_df.drop('New',axis=1)

W  X  Y  Z
A  7  5  3  5
B  1  3  2  4
C  3  4  0  3
D  6  6  9  0

In [ ]:
my_df # Still there when you call the df

W  X  Y  Z  New
A  7  5  3  5   12
B  1  3  2  4    5
C  3  4  0  3    6
D  6  6  9  0    6

13.  >Get rid of the new column Permanently

In [ ]:
my_df.drop('New',axis=1,inplace=True)

In [ ]:
my_df

W  X  Y  Z
A  7  5  3  5
B  1  3  2  4
C  3  4  0  3
D  6  6  9  0

14. >Get rid of the first row  TEMPORARILY

In [ ]:
my_df.drop('A',axis=0)

W  X  Y  Z
B  1  3  2  4
C  3  4  0  3
D  6  6  9  0

15. >Create a new row that sums values in row D and C

In [ ]:
my_df.loc['k']=my_df.loc['D']+my_df.loc['C']

In [ ]:
my_df

W   X  Y  Z
A  7   5  3  5
B  1   3  2  4
C  3   4  0  3
D  6   6  9  0
k  9  10  9  3

16. > Select rows A and K and columns X and Z data only

In [ ]:
my_df.loc[['A','k'],['X','Z']]  # Make sure you understand that the cases are sensitive ( K vs k)

X  Z
A   5  5
k  10  3

>> Conditinal selection

17. >Choose only values which are greater than 4 in your data frame

In [ ]:
my_df>4   # This is the condition which will generate a Boolean data Frame

W      X      Y      Z
A   True   True  False   True
B  False  False  False  False
C  False  False  False  False
D   True   True   True  False
k   True   True   True  False

Now, we apply the condition to our DataFrame

In [ ]:
my_df[my_df>4]      # use brackets in from of the data frame and put the condition in it

W     X    Y    Z
A  7.0   5.0  NaN  5.0
B  NaN   NaN  NaN  NaN
C  NaN   NaN  NaN  NaN
D  6.0   6.0  9.0  NaN
k  9.0  10.0  9.0  NaN

Can you make sense of what happening belwo?  Think about it

In [ ]:
my_df[my_df>4].dropna(axis=1)

Empty DataFrame
Columns: []
Index: [A, B, C, D, k]

In [ ]:
my_df[my_df>4].dropna(axis=0)

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

18. >Choose only values which are EVEN and GREATER than 2 in your data frame

In [ ]:
my_df   [   (my_df%2==0)    &    (my_df>2)   ]      # remember if Pandas unlike basic python, we use &  instead of AND

W     X   Y    Z
A  NaN   NaN NaN  NaN
B  NaN   NaN NaN  4.0
C  NaN   4.0 NaN  NaN
D  6.0   6.0 NaN  NaN
k  NaN  10.0 NaN  NaN

19. >Choose only values which are EVEN OR GREATER than 2 in your data frame

In [ ]:
my_df[(my_df%2==0) | (my_df>2)]     # remember if Pandas unlike basic python, we use | instead of or

W   X  Y  Z
A  7.0   5  3  5
B  NaN   3  2  4
C  3.0   4  0  3
D  6.0   6  9  0
k  9.0  10  9  3

> I want you to pay attention to the isnull() function and think about what it is doing

In [ ]:
my_df[(my_df%2==0) & (my_df>2)]

W     X   Y    Z
A  NaN   NaN NaN  NaN
B  NaN   NaN NaN  4.0
C  NaN   4.0 NaN  NaN
D  6.0   6.0 NaN  NaN
k  NaN  10.0 NaN  NaN

In [ ]:
my_df[(my_df%2==0) & (my_df>2)] .isnull()

W      X     Y      Z
A   True   True  True   True
B   True   True  True  False
C   True  False  True   True
D  False  False  True   True
k   True  False  True   True

In [ ]:
my_df[(my_df%2==0) | (my_df>2)] .isnull()

W      X      Y      Z
A  False  False  False  False
B   True  False  False  False
C  False  False  False  False
D  False  False  False  False
k  False  False  False  False

20. >What is fillna() function doing?  

In [ ]:
my_df[(my_df%2==0) & (my_df>2)].fillna(-10)

W     X     Y     Z
A -10.0 -10.0 -10.0 -10.0
B -10.0 -10.0 -10.0   4.0
C -10.0   4.0 -10.0 -10.0
D   6.0   6.0 -10.0 -10.0
k -10.0  10.0 -10.0 -10.0

In [ ]:
my_df[(my_df%2==0) & (my_df>2)].fillna(1000)

W       X       Y       Z
A  1000.0  1000.0  1000.0  1000.0
B  1000.0  1000.0  1000.0     4.0
C  1000.0     4.0  1000.0  1000.0
D     6.0     6.0  1000.0  1000.0
k  1000.0    10.0  1000.0  1000.0

In [ ]:
my_df[(my_df%2==0) & (my_df>2)].fillna(my_df['W'].mean())

W     X    Y    Z
A  5.2   5.2  5.2  5.2
B  5.2   5.2  5.2  4.0
C  5.2   4.0  5.2  5.2
D  6.0   6.0  5.2  5.2
k  5.2  10.0  5.2  5.2

In [ ]:
my_df['W'].mean()

5.2